In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [22]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold

# data = pd.read_csv("/gdrive/MyDrive/Colab/SleepHelper/noWakeData1.csv")
data = pd.read_csv("/gdrive/MyDrive/Colab/SleepHelper/noWakeData.csv")
data.columns
data.count()

# data = (data - np.min(data)) / (np.max(data) - np.min(data)).values

dataset = data.values
x = dataset[:,0:11]
y = dataset[:,11]

number_of_train = int(len(dataset)*0.8)

train_x = x[:number_of_train]
train_y = y[:number_of_train]
test_x = x[number_of_train:]
test_y = y[number_of_train:]

train_y=tf.keras.utils.to_categorical(train_y)
test_y=tf.keras.utils.to_categorical(test_y)

print(train_y)

# print(test_y)
# seed=0
# np.random.seed(seed)
# tf.set_random_seed(seed)

# n_fold=10
# skf=StratifiedKFold(n_splits=n_fold, shuffle=True)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [21]:
# 모델의 설정

model = Sequential()
model.add(Dense(30,  input_dim=11, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(6, activation='softmax'))

# 모델 컴파일
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

# 모델 실행
model.fit(train_x, train_y, epochs=1000, batch_size=100)

model.save('/gdrive/MyDrive/Colab/SleepHelper/SleepHelper1.h5')

# 결과 출력
print("\n Accuracy: %.4f" % (model.evaluate(test_x, test_y)[1]))

Epoch 1/1000
22/22 [==============================] - 1s 4ms/step - loss: 24.7152 - accuracy: 0.4006
Epoch 2/1000
22/22 [==============================] - 0s 6ms/step - loss: 9.1440 - accuracy: 0.3517
Epoch 3/1000
22/22 [==============================] - 0s 6ms/step - loss: 4.7708 - accuracy: 0.4176
Epoch 4/1000
22/22 [==============================] - 0s 6ms/step - loss: 3.2559 - accuracy: 0.4636
Epoch 5/1000
22/22 [==============================] - 0s 9ms/step - loss: 2.5612 - accuracy: 0.4807
Epoch 6/1000
22/22 [==============================] - 0s 7ms/step - loss: 2.1477 - accuracy: 0.4461
Epoch 7/1000
22/22 [==============================] - 0s 10ms/step - loss: 1.8264 - accuracy: 0.4733
Epoch 8/1000
22/22 [==============================] - 0s 6ms/step - loss: 1.5511 - accuracy: 0.4903
Epoch 9/1000
22/22 [==============================] - 0s 8ms/step - loss: 1.4592 - accuracy: 0.5212
Epoch 10/1000
22/22 [==============================] - 0s 4ms/step - loss: 1.4055 - accuracy: 0.51